export const HOST_WILLIAM = '192.168.1.32'
export const HOST_DAVID = '192.168.1.97'
export const HOST = HOST_DAVID
export const PORT = 3002

export const MESSAGE_FROM_CLIENT = 'MESSAGE_FROM_CLIENT'
export const MESSAGE_TO_EXTENSION = 'MESSAGE_TO_EXTENSION'
export const MESSAGE_FROM_EXTENSION = 'MESSAGE_FROM_EXTENSION'
export const MESSAGE_FROM_SERVER = 'MESSAGE_FROM_SERVER'