
export const LOCAL_PORT = 3002
export const IO_SERVER = HEROKU_HOST || `http://${LOCAL_HOST}:${LOCAL_PORT}`
export const MESSAGE_FROM_CLIENT = 'MESSAGE_FROM_CLIENT'
export const MESSAGE_TO_EXTENSION = 'MESSAGE_TO_EXTENSION'
export const MESSAGE_FROM_EXTENSION = 'MESSAGE_FROM_EXTENSION'
